PugPic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

# MEDIA_ROOTを公開する（アクセス可能にする）
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'app'
urlpatterns = [
  path('', views.index, name='index'),
  path('users/<int:pk>/', views.users_detail, name='users_detail'),
  path('photos/new/', views.photos_new, name='photos_new'),
  path('photos/<int:pk>/', views.photos_detail, name="photos_detail"),
  path('photos/<int:pk>/delete/', views.photos_delete, name='photos_delete'),
  path('signup/', views.signup, name='signup'),
  path('login/', auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User

class Photo(models.Model):
    #title = models.CharField(max_length=150)
    image = models.ImageField(upload_to='photos')
    comment = models.TextField(max_length=200, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

app/forms.py
from django.forms import ModelForm
from .models import Photo

class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = ['image', 'comment']

app/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.models import User

# ページネーション
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings

def paginate_query(request, queryset, count):
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj

# トップページ
from .models import Photo

def index(request):
    photos = Photo.objects.all().order_by('-created_at')
    page_obj = paginate_query(request, photos, settings.PAGE_PER_ITEM)
    return render(request, 'app/index.html', {'page_obj': page_obj})

# ユーザー詳細ページ
def users_detail(request, pk):
  user = get_object_or_404(User, pk=pk)
  photos = user.photo_set.all().order_by('-created_at')
  return render(request, 'app/users_detail.html', {'user': user, 'photos': photos})

# 新規登録ページ
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            input_username = form.cleaned_data['username']
            input_password = form.cleaned_data['password1']
            new_user = authenticate(username=input_username, password=input_password)
            if new_user is not None:
                login(request, new_user)
                return redirect('app:users_detail', pk=new_user.pk)
    else:
        form = UserCreationForm()
    return render(request, 'app/signup.html', {'form': form})

# 新規投稿ページ
from django.contrib.auth.decorators import login_required
from .forms import PhotoForm
from django.contrib import messages

@login_required
def photos_new(request):
    if request.method == "POST":
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)
            photo.user = request.user
            photo.save()
            messages.success(request, "投稿が完了しました！")
            return redirect('app:users_detail', pk=request.user.pk)
    else:
        form = PhotoForm()
        return render(request, 'app/photos_new.html', {'form': form})

# 写真詳細ページ
def photos_detail(request, pk):
    photo = get_object_or_404(Photo, pk=pk)
    return render(request, 'app/photos_detail.html', {'photo': photo})

# 写真削除
from django.views.decorators.http import require_POST

@require_POST
def photos_delete(request, pk):
    photo = get_object_or_404(Photo, pk=pk)
    photo.delete()
    return redirect('app:users_detail', request.user.id)

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PugPic | パグ好きのための写真投稿サイト</title>
<meta name="description" content="パグ好きのための写真投稿サイト">
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@nochifuchi1" />
<meta property="og:title" content="PugPic | パグ好きのための写真投稿サイト" />
<meta property="og:url" content="https://pugpic-django.herokuapp.com" />
<meta property="og:image" content="https://pugpic-django.herokuapp.com/static/img/pugpic_ogp.jpg" />
<meta property="og:site_name" content="PugPic" />
<meta property="og:description" content="パグ好きのための写真投稿サイト" />
<link rel="shortcut icon" href="/static/img/favicon.ico" />
<link rel="icon" href="/static/img/favicon.png" />
<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
<link rel="stylesheet" type="text/css" href="{% block css %}{% endblock %}">
<script src="{% static 'js/lib/jquery-3.4.0.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
<!-- Adobe Font -->
<script>
  (function(d) {
    var config = {
      kitId: 'dje8mib',
      scriptTimeout: 3000,
      async: true
    },
    h=d.documentElement,t=setTimeout(function(){h.className=h.className.replace(/\bwf-loading\b/g,"")+" wf-inactive";},config.scriptTimeout),tk=d.createElement("script"),f=false,s=d.getElementsByTagName("script")[0],a;h.className+=" wf-loading";tk.src='https://use.typekit.net/'+config.kitId+'.js';tk.async=true;tk.onload=tk.onreadystatechange=function(){a=this.readyState;if(f||a&&a!="complete"&&a!="loaded")return;f=true;clearTimeout(t);try{Typekit.load(config)}catch(e){}};s.parentNode.insertBefore(tk,s)
  })(document);
</script>
<!-- /Adobe Font -->
</head>
<body>
  <div id="app">

    <!-- header -->
    <header>
      <div class="header-heading">
        <div class="container">パグ好きのための写真投稿サイト</div>
      </div>
      <div class="header-main">
        <div class="container">
          <h1><a href="{% url 'app:index' %}">PugPic</a></h1>
          <nav class="header-menu">
            <ul>
              {% if request.user.is_authenticated %}
              <li><a class="btn" href="{% url 'app:photos_new' %}">投稿</a></li>
              <li><a class="btn" href="{% url 'app:users_detail' request.user.id %}">マイページ</a></li>
              <li><a class="btn" href="{% url 'app:logout' %}">ログアウト</a></li>
              {% else %}
              <li><a class="btn" href="{% url 'app:signup' %}">新規登録</a></li>
              <li><a class="btn" href="{% url 'app:login' %}">ログイン</a></li>
              {% endif %}
            </ul>
          </nav>
          <!-- sp -->
          <div class="sp-header-menu">
            <div class="nav-trigger">
              <a href="">
                <span></span>
                <span></span>
                <span></span>
              </a>
            </div>
            <nav>
              <ul>
                <li><a href="{% url 'app:index' %}">HOME</a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'app:photos_new' %}">投稿</a></li>
                <li><a href="{% url 'app:users_detail' request.user.id %}">マイページ</a></li>
                <li><a href="{% url 'app:logout' %}">ログアウト</a></li>
                {% else %}
                <li><a href="{% url 'app:signup' %}">新規登録</a></li>
                <li><a href="{% url 'app:login' %}">ログイン</a></li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </header>
    <!-- /header -->

    <div id="contents">
      <div id="main">
        <div class="container">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>

    <!-- footer -->
    <footer>
      <div class="container">
        <small>©2019&nbsp;PugPic&nbsp;All&nbsp;Rights&nbsp;Reserved.</small>
      </div>
    </footer>
    <!-- /footer -->

  </div>
</body>
</html>

app/templates/app/index.html
{% extends 'app/base.html' %}

{% load static %}

{% block content %}

<!-- sec-photo -->
<section id="sec-photo">
  <ul class="photo-lists">
    {% for photo in page_obj %}
      <li>
        <div class="user icon-layout">
          <a href="{% url 'app:users_detail' photo.user.id %}">
            <span class="icon"><img class="img-circle" src="{% static 'img/user.svg' %}" alt=""></span>
            <span class="user-name">{{ photo.user }}</span>
          </a>
        </div>
        <div class="photo">
          <a href="{% url 'app:photos_detail' photo.id %}"><img class="img-responsive" src="{{ photo.image.url }}" alt=""></a>
        </div>
        <ul class="photo-info">
          <li class="user-name">{{ photo.user }}</li>
          <li class="comment">{{ photo.comment | linebreaks | urlize }}</li>
          <li class="update">{{ photo.created_at }} UP</li>
        </ul>
      </li>
    {% endfor %}
  </ul>
</section>
<!-- /sec-photo -->

{% include "app/pagination.html" %}

{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}

{% block content %}

<!-- sec-login -->
<section id="sec-login" class="section">
  <div class="form-inner">
    <form class="form-login form-layout" method="POST">{% csrf_token %}
      <h2>ログイン</h2>
      {% if form.errors %}
        <p class="form-error">ユーザー名かパスワードが間違っています。<br>もう一度入力してください。</p>
      {% endif %}
      <ul class="form-lists">
        <li>
          <div class="title">ユーザ名</div>
          <input class="input-style" type="text" name="username">
        </li>
        <li>
          <div class="title">パスワード</div>
          <input class="input-style" type="password" name="password">
        </li>
      </ul>
      <input class="btn" type="submit" value="ログイン">
    </form>
    <div class="signup-link"><a class="line-hover" href="{% url 'app:signup' %}">新規登録はこちら</a></div>
  </div>
</section>
<!-- /sec-login -->

{% endblock %}

app/templates/app/pagination.html
<div class="pagination">
  <ul class="pagination-lists">
    {% if page_obj.has_previous %}
    <li class="prev"><a href="?page={{ page_obj.previous_page_number }}"></a></li>
    {% endif %}

    {% for link_page in page_obj.paginator.page_range %}
      {% if link_page == page_obj.number %}
      <li class="current-page disabled"><a href="#">{{ link_page }}</a></li>
      {% else %}
      <li class="link-page"><a href="?page={{ link_page }}">{{ link_page }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="next"><a href="?page={{ page_obj.next_page_number }}"></a></li>
    {% endif %}
  </ul>
</div>

app/templates/app/photos_detail.html
{% extends 'app/base.html' %}

<!-- テンプレート毎のCSSファイル読み込み -->
{% load static %}
{% block css %}{% static 'css/photos_detail.css' %}{% endblock %}

{% block content %}

<!-- sec-photo -->
<section id="sec-photo" class="section">
  <div class="inner">
    <div class="photo"><img class="img-responsive" src="{{ photo.image.url }}" alt=""></div>
    <div class="photo-info">
      <div class="user icon-layout">
        <a href="{% url 'app:users_detail' photo.user.id %}">
          <span class="icon"><img class="img-circle" src="{% static 'img/user.svg' %}" alt=""></span>
          <span class="user-name">{{ photo.user }}</span>
        </a>
      </div>
      <div class="comment">{{ photo.comment }}</div>
      {% if request.user == photo.user %}
      <!-- 削除ボタン -->
      <form method="POST" action="{% url 'app:photos_delete' photo.id %}">
        {% csrf_token %}
        <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
      </form>
      {% endif %}
    </div>
  </div>
</section>
<!-- /sec-photo -->

{% endblock %}

app/templates/app/photos_new.html
{% extends 'app/base.html' %}

<!-- テンプレート毎のCSSファイル読み込み -->
{% load static %}
{% block css %}{% static 'css/photos_new.css' %}{% endblock %}

{% block content %}

<!-- sec-photos-new -->
<section id="sec-photos-new" class="section">
  <form method="POST" action="{% url 'app:photos_new' %}" enctype="multipart/form-data">{% csrf_token %}
    <ul class="form-lists">
      <li>
        <div class="form-title"><span></span>画像</div>
        <div class="image"><label class="btn" for="id_image">写真を選択{{ form.image }}</label></div>
      </li>
      <li>
        <div class="form-title"><span></span>コメント</div>
        <div>{{ form.comment }}</div>
      </li>
    </ul>
    <button type="submit" class="btn">保存</button>
  </form>
</section>
<!-- /sec-photos-new -->

{% endblock %}

app/templates/app/signup.html
{% extends 'app/base.html' %}

{% block content %}

<!-- sec-signup -->
<section id="sec-signup" class="section">
  <div class="form-inner">
    <form class="form-signup form-layout" method="POST" action="{% url 'app:signup' %}">
      {% csrf_token %}
      <h2>新規登録</h2>
      <ul class="form-lists">
        <li>
          <div class="title">ユーザー名</div>
          {{ form.username }}
          {{ form.username.errors }}
        </li>
        <li>
          <div class="title">パスワード</div>
          {{ form.password1 }}
          {{ form.password1.errors }}
        </li>
        <li>
          <div class="title">パスワード（確認）</div>
          {{ form.password2 }}
          {{ form.password2.errors }}
        </li>
      </ul>
      <input class="btn" type="submit" value="登録する">
    </form>
    <div class="login-link"><a class="line-hover" href="{% url 'app:login' %}">ログインはこちら</a></div>
  </div>
</section>
<!-- /sec-signup -->

{% endblock %}

app/templates/app/users_detail.html
{% extends 'app/base.html' %}

<!-- テンプレート毎のCSSファイル読み込み -->
{% load static %}
{% block css %}{% static 'css/users_detail.css' %}{% endblock %}

{% block content %}

{% for message in messages %}
  <p class="message-success">{{ message }}</p>
{% endfor %}

<!-- sec-user -->
<section id="sec-user" class="section">
  <div class="user-info">
    <div class="icon"><img class="img-circle" src="{% static 'img/user.svg' %}" alt=""></div>
    <div class="user-detail">
      <div class="user-name">@{{ user.username }}</div>
      <div class="post">
        {% if photos.count != 0 %}
          <p>投稿 <span>{{ photos.count }}</span> 件</p>
        {% else %}
          {% if user == request.user %}
            <p>初めての投稿をしてみましょう！</p>
          {% else %}
            <p>@{{ user.username }}さんはまだ投稿してません。</p>
          {% endif %}
        {% endif %}
      </div>
    </div>
  </div>
</section>
<!-- /sec-user -->

<!-- sec-photo -->
<section id="sec-photo">
  <ul class="photo-lists">
    {% for photo in photos %}
      <li>
        <div class="photo">
          <a href="{% url 'app:photos_detail' photo.id %}"><img class="img-responsive" src="{{ photo.image.url }}" alt=""></a>
        </div>
      </li>
    {% endfor %}
  </ul>
</section>
<!-- /sec-photo -->

{% endblock %}